version: "3.9"

services:

  mongodb:
    image: mongo:5
    restart: always
    container_name: mongodb
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_ROOT_PW
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db
      - ./:/app
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/app/key/mongo_key_file", "--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongonet

volumes:
  mongodata:


networks:
  mongonet:

