global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

api:
  dashboard: true
  
  # solo se non si usa la dashboard protetta
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

providers:
  docker:
      exposedbydefault: false

  file:
    directory: /etc/traefik
    watch: true

# Overwrite Default Certificates
tls:
  certificates:
    - certFile: /certs/xxx.lan.crt
      keyFile: /certs/xxx.lan.key


# Configure your CertificateResolver here...
# ---
# certificatesResolvers:
#   production_resolver:
#     acme:
#       email: your-email@example.com
#       storage: /letsencrypt/acme.json
#       caServer: "https://acme-v02.api.letsencrypt.org/directory"

#       # httpChallenge:
#       #   entryPoint: web

#       tlschallenge: true

########################################################
